UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/DartConfiguration.tcl
UpdateCTestConfiguration  from :/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/DartConfiguration.tcl
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
      Start  1: incorrect_solution_tests

1: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/incorrect_solution_tests
1: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build
1: Test timeout computed to be: 5
1: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/_deps/googletest-src/googletest/src/gtest_main.cc
1: [==========] Running 4 tests from 1 test suite.
1: [----------] Global test environment set-up.
1: [----------] 4 tests from FileSystemTest
1: [ RUN      ] FileSystemTest.ListFilesInDirectory
1: [       OK ] FileSystemTest.ListFilesInDirectory (0 ms)
1: [ RUN      ] FileSystemTest.EdgeCases
1: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/test.cpp:36: Failure
1: Value of: fs.filePathExists("/trailing/slashes/")
1:   Actual: true
1: Expected: false
1: 
1: [  FAILED  ] FileSystemTest.EdgeCases (0 ms)
1: [ RUN      ] FileSystemTest.AddFilePathValid
1: [       OK ] FileSystemTest.AddFilePathValid (0 ms)
1: [ RUN      ] FileSystemTest.AddFilePathInvalid
1: [       OK ] FileSystemTest.AddFilePathInvalid (0 ms)
1: [----------] 4 tests from FileSystemTest (0 ms total)
1: 
1: [----------] Global test environment tear-down
1: [==========] 4 tests from 1 test suite ran. (0 ms total)
1: [  PASSED  ] 3 tests.
1: [  FAILED  ] 1 test, listed below:
1: [  FAILED  ] FileSystemTest.EdgeCases
1: 
1:  1 FAILED TEST
 1/11 Test  #1: incorrect_solution_tests .........***Failed    0.46 sec
test 2
      Start  2: model1_tests

2: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model1_tests
2: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build
2: Test timeout computed to be: 5
2: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/_deps/googletest-src/googletest/src/gtest_main.cc
2: [==========] Running 4 tests from 1 test suite.
2: [----------] Global test environment set-up.
2: [----------] 4 tests from FileSystemTest
2: [ RUN      ] FileSystemTest.ListFilesInDirectory
2: [       OK ] FileSystemTest.ListFilesInDirectory (0 ms)
2: [ RUN      ] FileSystemTest.EdgeCases
2: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/test.cpp:36: Failure
2: Value of: fs.filePathExists("/trailing/slashes/")
2:   Actual: true
2: Expected: false
2: 
2: [  FAILED  ] FileSystemTest.EdgeCases (0 ms)
2: [ RUN      ] FileSystemTest.AddFilePathValid
2: [       OK ] FileSystemTest.AddFilePathValid (0 ms)
2: [ RUN      ] FileSystemTest.AddFilePathInvalid
2: [       OK ] FileSystemTest.AddFilePathInvalid (0 ms)
2: [----------] 4 tests from FileSystemTest (0 ms total)
2: 
2: [----------] Global test environment tear-down
2: [==========] 4 tests from 1 test suite ran. (0 ms total)
2: [  PASSED  ] 3 tests.
2: [  FAILED  ] 1 test, listed below:
2: [  FAILED  ] FileSystemTest.EdgeCases
2: 
2:  1 FAILED TEST
 2/11 Test  #2: model1_tests .....................***Failed    0.32 sec
test 3
      Start  3: model10_tests

3: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model10_tests
3: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build
3: Test timeout computed to be: 5
3: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/_deps/googletest-src/googletest/src/gtest_main.cc
3: [==========] Running 4 tests from 1 test suite.
3: [----------] Global test environment set-up.
3: [----------] 4 tests from FileSystemTest
3: [ RUN      ] FileSystemTest.ListFilesInDirectory
3: [       OK ] FileSystemTest.ListFilesInDirectory (0 ms)
3: [ RUN      ] FileSystemTest.EdgeCases
3: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/test.cpp:36: Failure
3: Value of: fs.filePathExists("/trailing/slashes/")
3:   Actual: true
3: Expected: false
3: 
3: [  FAILED  ] FileSystemTest.EdgeCases (0 ms)
3: [ RUN      ] FileSystemTest.AddFilePathValid
3: [       OK ] FileSystemTest.AddFilePathValid (0 ms)
3: [ RUN      ] FileSystemTest.AddFilePathInvalid
3: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/test.cpp:75: Failure
3: Expected: fs.addFilePath("a/c.txt") throws an exception of type std::invalid_argument.
3:   Actual: it throws nothing.
3: 
3: [  FAILED  ] FileSystemTest.AddFilePathInvalid (0 ms)
3: [----------] 4 tests from FileSystemTest (0 ms total)
3: 
3: [----------] Global test environment tear-down
3: [==========] 4 tests from 1 test suite ran. (0 ms total)
3: [  PASSED  ] 2 tests.
3: [  FAILED  ] 2 tests, listed below:
3: [  FAILED  ] FileSystemTest.EdgeCases
3: [  FAILED  ] FileSystemTest.AddFilePathInvalid
3: 
3:  2 FAILED TESTS
 3/11 Test  #3: model10_tests ....................***Failed    0.32 sec
test 4
      Start  4: model2_tests

4: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model2_tests
4: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build
4: Test timeout computed to be: 5
4: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/_deps/googletest-src/googletest/src/gtest_main.cc
4: [==========] Running 4 tests from 1 test suite.
4: [----------] Global test environment set-up.
4: [----------] 4 tests from FileSystemTest
4: [ RUN      ] FileSystemTest.ListFilesInDirectory
4: [       OK ] FileSystemTest.ListFilesInDirectory (0 ms)
4: [ RUN      ] FileSystemTest.EdgeCases
4: [       OK ] FileSystemTest.EdgeCases (0 ms)
4: [ RUN      ] FileSystemTest.AddFilePathValid
4: [       OK ] FileSystemTest.AddFilePathValid (0 ms)
4: [ RUN      ] FileSystemTest.AddFilePathInvalid
4: [       OK ] FileSystemTest.AddFilePathInvalid (0 ms)
4: [----------] 4 tests from FileSystemTest (0 ms total)
4: 
4: [----------] Global test environment tear-down
4: [==========] 4 tests from 1 test suite ran. (0 ms total)
4: [  PASSED  ] 4 tests.
 4/11 Test  #4: model2_tests .....................   Passed    0.38 sec
test 5
      Start  5: model3_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model3_tests
Looked in the following places:
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/TesUnable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model3_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model4_tests
ter_cpp_codebench/tasks/621262/build/Deployment/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model3_tests

5: Test command: 
5: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build
 5/11 Test  #5: model3_tests .....................***Not Run   0.00 sec
test 6
      Start  6: model4_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model4_tests
Looked in the following places:
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model4_tests

6: Test command: 
6: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build
 6/11 Test  #6: model4_tests .....................***Not Run   0.00 sec
test 7
      Start  7: model5_tests

7: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model5_tests
7: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build
7: Test timeout computed to be: 5
7: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/_deps/googletest-src/googletest/src/gtest_main.cc
7: [==========] Running 4 tests from 1 test suite.
7: [----------] Global test environment set-up.
7: [----------] 4 tests from FileSystemTest
7: [ RUN      ] FileSystemTest.ListFilesInDirectory
7: unknown file: Failure
7: C++ exception with description "Cannot create file in path that conflicts with existing file" thrown in the test body.
7: 
7: [  FAILED  ] FileSystemTest.ListFilesInDirectory (0 ms)
7: [ RUN      ] FileSystemTest.EdgeCases
7: unknown file: Failure
7: C++ exception with description "Cannot create file in path that conflicts with existing file" thrown in the test body.
7: 
7: [  FAILED  ] FileSystemTest.EdgeCases (0 ms)
7: [ RUN      ] FileSystemTest.AddFilePathValid
7: unknown file: Failure
7: C++ exception with description "Path conflicts with existing file" thrown in the test body.
7: 
7: [  FAILED  ] FileSystemTest.AddFilePathValid (0 ms)
7: [ RUN      ] FileSystemTest.AddFilePathInvalid
7: [       OK ] FileSystemTest.AddFilePathInvalid (0 ms)
7: [----------] 4 tests from FileSystemTest (0 ms total)
7: 
7: [----------] Global test environment tear-down
7: [==========] 4 tests from 1 test suite ran. (0 ms total)
7: [  PASSED  ] 1 test.
7: [  FAILED  ] 3 tests, listed below:
7: [  FAILED  ] FileSystemTest.ListFilesInDirectory
7: [  FAILED  ] FileSystemTest.EdgeCases
7: [  FAILED  ] FileSystemTest.AddFilePathValid
7: 
7:  3 FAILED TESTS
 7/11 Test  #7: model5_tests .....................***Failed    0.42 sec
test 8
      Start  8: model6_tests

8: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model6_tests
8: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build
8: Test timeout computed to be: 5
8: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/_deps/googletest-src/googletest/src/gtest_main.cc
8: [==========] Running 4 tests from 1 test suite.
8: [----------] Global test environment set-up.
8: [----------] 4 tests from FileSystemTest
8: [ RUN      ] FileSystemTest.ListFilesInDirectory
8: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/test.cpp:16: Failure
8: Expected equality of these values:
8:   sortedResult
8:     Which is: {}
8:   (std::vector<std::string>{"/a/b/c.txt", "/a/b/d.txt"})
8:     Which is: { "/a/b/c.txt", "/a/b/d.txt" }
8: 
8: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/test.cpp:18: Failure
8: Expected equality of these values:
8:   fs.listFilesInDirectory("/a/e")
8:     Which is: {}
8:   (std::vector<std::string>{"/a/e/f.txt"})
8:     Which is: { "/a/e/f.txt" }
8: 
8: [  FAILED  ] FileSystemTest.ListFilesInDirectory (0 ms)
8: [ RUN      ] FileSystemTest.EdgeCases
8: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/test.cpp:28: Failure
8: Expected equality of these values:
8:   fs.listFilesInDirectory("/a/")
8:     Which is: {}
8:   std::vector<std::string>{"/a/bbb.txt"}
8:     Which is: { "/a/bbb.txt" }
8: 
8: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/test.cpp:36: Failure
8: Value of: fs.filePathExists("/trailing/slashes/")
8:   Actual: true
8: Expected: false
8: 
8: [  FAILED  ] FileSystemTest.EdgeCases (0 ms)
8: [ RUN      ] FileSystemTest.AddFilePathValid
8: [       OK ] FileSystemTest.AddFilePathValid (0 ms)
8: [ RUN      ] FileSystemTest.AddFilePathInvalid
8: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/test.cpp:72: Failure
8: Expected: fs.addFilePath("/a/b") throws an exception of type std::invalid_argument.
8:   Actual: it throws nothing.
8: 
8: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/test.cpp:75: Failure
8: Expected: fs.addFilePath("a/c.txt") throws an exception of type std::invalid_argument.
8:   Actual: it throws nothing.
8: 
8: [  FAILED  ] FileSystemTest.AddFilePathInvalid (0 ms)
8: [----------] 4 tests from FileSystemTest (0 ms total)
8: 
8: [----------] Global test environment tear-down
8: [==========] 4 tests from 1 test suite ran. (0 ms total)
8: [  PASSED  ] 1 test.
8: [  FAILED  ] 3 tests, listed below:
8: [  FAILED  ] FileSystemTest.ListFilesInDirectory
8: [  FAILED  ] FileSystemTest.EdgeCases
8: [  FAILED  ] FileSystemTest.AddFilePathInvalid
8: 
8:  3 FAILED TESTS
 8/11 Test  #8: model6_tests .....................***Failed    0.33 sec
test 9
      Start  9: model7_tests

9: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model7_tests
9: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build
9: Test timeout computed to be: 5
9: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/_deps/googletest-src/googletest/src/gtest_main.cc
9: [==========] Running 4 tests from 1 test suite.
9: [----------] Global test environment set-up.
9: [----------] 4 tests from FileSystemTest
9: [ RUN      ] FileSystemTest.ListFilesInDirectory
9: [       OK ] FileSystemTest.ListFilesInDirectory (0 ms)
9: [ RUN      ] FileSystemTest.EdgeCases
9: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/taUnable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model8_tests
sks/621262/test.cpp:28: Failure
9: Expected equality of these values:
9:   fs.listFilesInDirectory("/a/")
9:     Which is: { "/a/bbb.txt", "/a/bb/d.txt", "/a/b/c.txt" }
9:   std::vector<std::string>{"/a/bbb.txt"}
9:     Which is: { "/a/bbb.txt" }
9: 
9: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/test.cpp:36: Failure
9: Value of: fs.filePathExists("/trailing/slashes/")
9:   Actual: true
9: Expected: false
9: 
9: [  FAILED  ] FileSystemTest.EdgeCases (0 ms)
9: [ RUN      ] FileSystemTest.AddFilePathValid
9: [       OK ] FileSystemTest.AddFilePathValid (0 ms)
9: [ RUN      ] FileSystemTest.AddFilePathInvalid
9: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/test.cpp:75: Failure
9: Expected: fs.addFilePath("a/c.txt") throws an exception of type std::invalid_argument.
9:   Actual: it throws nothing.
9: 
9: [  FAILED  ] FileSystemTest.AddFilePathInvalid (0 ms)
9: [----------] 4 tests from FileSystemTest (0 ms total)
9: 
9: [----------] Global test environment tear-down
9: [==========] 4 tests from 1 test suite ran. (0 ms total)
9: [  PASSED  ] 2 tests.
9: [  FAILED  ] 2 tests, listed below:
9: [  FAILED  ] FileSystemTest.EdgeCases
9: [  FAILED  ] FileSystemTest.AddFilePathInvalid
9: 
9:  2 FAILED TESTS
 9/11 Test  #9: model7_tests .....................***Failed    0.31 sec
test 10
      Start 10: model8_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model8_tests
Looked in the following places:
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model8_tests

10: Test command: 
10: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build
10/11 Test #10: model8_tests .....................***Not Run   0.00 sec
test 11
      Start 11: model9_tests

11: Test command: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model9_tests
11: Working Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build
11: Test timeout computed to be: 5
11: Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/_deps/googletest-src/googletest/src/gtest_main.cc
11: [==========] Running 4 tests from 1 test suite.
11: [----------] Global test environment set-up.
11: [----------] 4 tests from FileSystemTest
11: [ RUN      ] FileSystemTest.ListFilesInDirectory
11: unknown file: Failure
11: C++ exception with description "File path conflicts with an existing directory path" thrown in the test body.
11: 
11: [  FAILED  ] FileSystemTest.ListFilesIErrors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
nDirectory (0 ms)
11: [ RUN      ] FileSystemTest.EdgeCases
11: unknown file: Failure
11: C++ exception with description "File path conflicts with an existing directory path" thrown in the test body.
11: 
11: [  FAILED  ] FileSystemTest.EdgeCases (0 ms)
11: [ RUN      ] FileSystemTest.AddFilePathValid
11: unknown file: Failure
11: C++ exception with description "File path already exists" thrown in the test body.
11: 
11: [  FAILED  ] FileSystemTest.AddFilePathValid (0 ms)
11: [ RUN      ] FileSystemTest.AddFilePathInvalid
11: [       OK ] FileSystemTest.AddFilePathInvalid (0 ms)
11: [----------] 4 tests from FileSystemTest (0 ms total)
11: 
11: [----------] Global test environment tear-down
11: [==========] 4 tests from 1 test suite ran. (0 ms total)
11: [  PASSED  ] 1 test.
11: [  FAILED  ] 3 tests, listed below:
11: [  FAILED  ] FileSystemTest.ListFilesInDirectory
11: [  FAILED  ] FileSystemTest.EdgeCases
11: [  FAILED  ] FileSystemTest.AddFilePathValid
11: 
11:  3 FAILED TESTS
11/11 Test #11: model9_tests .....................***Failed    0.36 sec

9% tests passed, 10 tests failed out of 11

Total Test time (real) =   2.90 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Failed)
	  2 - model1_tests (Failed)
	  3 - model10_tests (Failed)
	  5 - model3_tests (Not Run)
	  6 - model4_tests (Not Run)
	  7 - model5_tests (Failed)
	  8 - model6_tests (Failed)
	  9 - model7_tests (Failed)
	 10 - model8_tests (Not Run)
	 11 - model9_tests (Failed)
Test project /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build
      Start  1: incorrect_solution_tests
 1/11 Test  #1: incorrect_solution_tests .........***Failed    0.01 sec
      Start  2: model1_tests
 2/11 Test  #2: model1_tests .....................***Failed    0.01 sec
      Start  3: model10_tests
 3/11 Test  #3: model10_tests ....................***Failed    0.01 sec
      Start  4: model2_tests
 4/11 Test  #4: model2_tests .....................   Passed    0.01 sec
      Start  5: model3_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model3_tests
Looked in the following places:
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model3_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model3_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model3_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model3_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model3_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model3_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model3_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model3_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model3_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model3_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model3_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model3_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model3_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model3_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model3_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model3_tests
 5/11 Test  #5: model3_tests .....................***Not Run   0.00 sec
      Start  6: model4_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model4_tests
Looked in the following places:
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model4_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model4_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model4_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model4_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model4_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model4_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model4_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model4_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model4_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model4_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model4_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model4_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model4_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model4_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model4_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model4_tests
 6/11 Test  #6: model4_tests .....................***Not Run   0.00 sec
      Start  7: model5_tests
 7/11 Test  #7: model5_tests .....................***Failed    0.00 sec
      Start  8: model6_tests
 8/11 Test  #8: model6_tests .....................***Failed    0.00 sec
      Start  9: model7_tests
 9/11 Test  #9: model7_tests .....................***Failed    0.00 sec
      Start 10: model8_tests
Could not find executable /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model8_tests
Looked in the following places:
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model8_tests
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Release/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Debug/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/MinSizeRel/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/RelWithDebInfo/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Deployment/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model8_tests
Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Development/model8_tests
Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/model8_tests
10/11 Test #10: model8_tests .....................***Not Run   0.00 sec
      Start 11: model9_tests
11/11 Test #11: model9_tests .....................***Failed    0.00 sec

9% tests passed, 10 tests failed out of 11

Total Test time (real) =   0.05 sec

The following tests FAILED:
	  1 - incorrect_solution_tests (Failed)
	  2 - model1_tests (Failed)
	  3 - model10_tests (Failed)
	  5 - model3_tests (Not Run)
	  6 - model4_tests (Not Run)
	  7 - model5_tests (Failed)
	  8 - model6_tests (Failed)
	  9 - model7_tests (Failed)
	 10 - model8_tests (Not Run)
	 11 - model9_tests (Failed)
Errors while running CTest
Output from these tests are in: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/621262/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
