Start testing: Jan 31 22:23 +06
----------------------------------------------------------
1/11 Testing: incorrect_solution_tests
1/11 Test: incorrect_solution_tests
Command: "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/incorrect_solution_tests"
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
"incorrect_solution_tests" start time: Jan 31 22:23 +06
Output:
----------------------------------------------------------
Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 13 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from FreqBufferBasicTest
[ RUN      ] FreqBufferBasicTest.CapacityAndSize
[       OK ] FreqBufferBasicTest.CapacityAndSize (0 ms)
[ RUN      ] FreqBufferBasicTest.PutAndGet
[       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
[ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
[       OK ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
[----------] 3 tests from FreqBufferBasicTest (0 ms total)

[----------] 10 tests from FreqBufferExtendedTest
[ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
[       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
[ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
[       OK ] FreqBufferExtendedTest.Resize_DecreaseCapacity (0 ms)
[ RUN      ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:123: Failure
Expected: buffer.resize(-1) throws an exception of type std::runtime_error.
  Actual: it throws nothing.

/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:125: Failure
Expected equality of these values:
  buffer.capacity()
    Which is: 18446744073709551615
  3u
    Which is: 3

/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:135: Failure
Expected equality of these values:
  buffer.size()
    Which is: 1
  0u
    Which is: 0

[  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_Basic
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_Basic (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_Basic
[       OK ] FreqBufferExtendedTest.pop_least_used_Basic (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals
[       OK ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_MoreThanSize
[       OK ] FreqBufferExtendedTest.pop_least_used_MoreThanSize (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:297: Failure
Expected equality of these values:
  buffer.size()
    Which is: 0
  1u
    Which is: 1

unknown file: Failure
C++ exception with description "Key not found in FreqBuffer" thrown in the test body.

[  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative (0 ms)
[----------] 10 tests from FreqBufferExtendedTest (0 ms total)

[----------] Global test environment tear-down
[==========] 13 tests from 2 test suites ran. (0 ms total)
[  PASSED  ] 11 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
[  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative

 2 FAILED TESTS
<end of output>
Test time =   0.01 sec
----------------------------------------------------------
Test Failed.
"incorrect_solution_tests" end time: Jan 31 22:23 +06
"incorrect_solution_tests" time elapsed: 00:00:00
----------------------------------------------------------

2/11 Testing: model1_tests
2/11 Test: model1_tests
Command: "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model1_tests"
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
"model1_tests" start time: Jan 31 22:23 +06
Output:
----------------------------------------------------------
Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 13 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from FreqBufferBasicTest
[ RUN      ] FreqBufferBasicTest.CapacityAndSize
[       OK ] FreqBufferBasicTest.CapacityAndSize (0 ms)
[ RUN      ] FreqBufferBasicTest.PutAndGet
[       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
[ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
[       OK ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
[----------] 3 tests from FreqBufferBasicTest (0 ms total)

[----------] 10 tests from FreqBufferExtendedTest
[ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
[       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
[ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
[       OK ] FreqBufferExtendedTest.Resize_DecreaseCapacity (0 ms)
[ RUN      ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:123: Failure
Expected: buffer.resize(-1) throws an exception of type std::runtime_error.
  Actual: it throws nothing.

/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:125: Failure
Expected equality of these values:
  buffer.capacity()
    Which is: 18446744073709551615
  3u
    Which is: 3

/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:135: Failure
Expected equality of these values:
  buffer.size()
    Which is: 1
  0u
    Which is: 0

[  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_Basic
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_Basic (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_Basic
[       OK ] FreqBufferExtendedTest.pop_least_used_Basic (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals
[       OK ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_MoreThanSize
[       OK ] FreqBufferExtendedTest.pop_least_used_MoreThanSize (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:297: Failure
Expected equality of these values:
  buffer.size()
    Which is: 0
  1u
    Which is: 1

unknown file: Failure
C++ exception with description "Key not found in FreqBuffer" thrown in the test body.

[  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative (0 ms)
[----------] 10 tests from FreqBufferExtendedTest (0 ms total)

[----------] Global test environment tear-down
[==========] 13 tests from 2 test suites ran. (0 ms total)
[  PASSED  ] 11 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
[  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative

 2 FAILED TESTS
<end of output>
Test time =   0.01 sec
----------------------------------------------------------
Test Failed.
"model1_tests" end time: Jan 31 22:23 +06
"model1_tests" time elapsed: 00:00:00
----------------------------------------------------------

3/11 Testing: model10_tests
3/11 Test: model10_tests
Command: "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model10_tests"
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
"model10_tests" start time: Jan 31 22:23 +06
Output:
----------------------------------------------------------
Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 13 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from FreqBufferBasicTest
[ RUN      ] FreqBufferBasicTest.CapacityAndSize
[       OK ] FreqBufferBasicTest.CapacityAndSize (0 ms)
[ RUN      ] FreqBufferBasicTest.PutAndGet
[       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
[ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
[       OK ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
[----------] 3 tests from FreqBufferBasicTest (0 ms total)

[----------] 10 tests from FreqBufferExtendedTest
[ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
[       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
[ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
[       OK ] FreqBufferExtendedTest.Resize_DecreaseCapacity (0 ms)
[ RUN      ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:123: Failure
Expected: buffer.resize(-1) throws an exception of type std::runtime_error.
  Actual: it throws nothing.

/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:125: Failure
Expected equality of these values:
  buffer.capacity()
    Which is: 18446744073709551615
  3u
    Which is: 3

<end of output>
Test time =   0.02 sec
----------------------------------------------------------
Test Failed.
"model10_tests" end time: Jan 31 22:23 +06
"model10_tests" time elapsed: 00:00:00
----------------------------------------------------------

4/11 Testing: model2_tests
4/11 Test: model2_tests
Command: "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model2_tests"
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
"model2_tests" start time: Jan 31 22:23 +06
Output:
----------------------------------------------------------
Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 13 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from FreqBufferBasicTest
[ RUN      ] FreqBufferBasicTest.CapacityAndSize
[       OK ] FreqBufferBasicTest.CapacityAndSize (0 ms)
[ RUN      ] FreqBufferBasicTest.PutAndGet
[       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
[ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
[       OK ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
[----------] 3 tests from FreqBufferBasicTest (0 ms total)

[----------] 10 tests from FreqBufferExtendedTest
[ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
[       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
[ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
[       OK ] FreqBufferExtendedTest.Resize_DecreaseCapacity (0 ms)
[ RUN      ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:123: Failure
Expected: buffer.resize(-1) throws an exception of type std::runtime_error.
  Actual: it throws nothing.

/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:125: Failure
Expected equality of these values:
  buffer.capacity()
    Which is: 18446744073709551615
  3u
    Which is: 3

/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:135: Failure
Expected equality of these values:
  buffer.size()
    Which is: 1
  0u
    Which is: 0

[  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_Basic
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_Basic (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_Basic
[       OK ] FreqBufferExtendedTest.pop_least_used_Basic (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals
[       OK ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_MoreThanSize
[       OK ] FreqBufferExtendedTest.pop_least_used_MoreThanSize (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:297: Failure
Expected equality of these values:
  buffer.size()
    Which is: 0
  1u
    Which is: 1

unknown file: Failure
C++ exception with description "Key not found in FreqBuffer" thrown in the test body.

[  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative (0 ms)
[----------] 10 tests from FreqBufferExtendedTest (0 ms total)

[----------] Global test environment tear-down
[==========] 13 tests from 2 test suites ran. (0 ms total)
[  PASSED  ] 11 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
[  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative

 2 FAILED TESTS
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Failed.
"model2_tests" end time: Jan 31 22:23 +06
"model2_tests" time elapsed: 00:00:00
----------------------------------------------------------

5/11 Testing: model3_tests
5/11 Test: model3_tests
Command: "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model3_tests"
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
"model3_tests" start time: Jan 31 22:23 +06
Output:
----------------------------------------------------------
Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 13 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from FreqBufferBasicTest
[ RUN      ] FreqBufferBasicTest.CapacityAndSize
[       OK ] FreqBufferBasicTest.CapacityAndSize (0 ms)
[ RUN      ] FreqBufferBasicTest.PutAndGet
[       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
[ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
[       OK ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
[----------] 3 tests from FreqBufferBasicTest (0 ms total)

[----------] 10 tests from FreqBufferExtendedTest
[ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
[       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
[ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
[       OK ] FreqBufferExtendedTest.Resize_DecreaseCapacity (0 ms)
[ RUN      ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:123: Failure
Expected: buffer.resize(-1) throws an exception of type std::runtime_error.
  Actual: it throws nothing.

/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:125: Failure
Expected equality of these values:
  buffer.capacity()
    Which is: 18446744073709551615
  3u
    Which is: 3

/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:135: Failure
Expected equality of these values:
  buffer.size()
    Which is: 1
  0u
    Which is: 0

[  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_Basic
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_Basic (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_Basic
[       OK ] FreqBufferExtendedTest.pop_least_used_Basic (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals
[       OK ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_MoreThanSize
[       OK ] FreqBufferExtendedTest.pop_least_used_MoreThanSize (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:297: Failure
Expected equality of these values:
  buffer.size()
    Which is: 0
  1u
    Which is: 1

unknown file: Failure
C++ exception with description "Key not found in FreqBuffer" thrown in the test body.

[  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative (0 ms)
[----------] 10 tests from FreqBufferExtendedTest (0 ms total)

[----------] Global test environment tear-down
[==========] 13 tests from 2 test suites ran. (0 ms total)
[  PASSED  ] 11 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
[  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative

 2 FAILED TESTS
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Failed.
"model3_tests" end time: Jan 31 22:23 +06
"model3_tests" time elapsed: 00:00:00
----------------------------------------------------------

6/11 Testing: model4_tests
6/11 Test: model4_tests
Command: "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model4_tests"
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
"model4_tests" start time: Jan 31 22:23 +06
Output:
----------------------------------------------------------
Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 13 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from FreqBufferBasicTest
[ RUN      ] FreqBufferBasicTest.CapacityAndSize
[       OK ] FreqBufferBasicTest.CapacityAndSize (0 ms)
[ RUN      ] FreqBufferBasicTest.PutAndGet
[       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
[ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
[       OK ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
[----------] 3 tests from FreqBufferBasicTest (0 ms total)

[----------] 10 tests from FreqBufferExtendedTest
[ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
[       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
[ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
[       OK ] FreqBufferExtendedTest.Resize_DecreaseCapacity (0 ms)
[ RUN      ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:123: Failure
Expected: buffer.resize(-1) throws an exception of type std::runtime_error.
  Actual: it throws nothing.

/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:125: Failure
Expected equality of these values:
  buffer.capacity()
    Which is: 18446744073709551615
  3u
    Which is: 3

/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:135: Failure
Expected equality of these values:
  buffer.size()
    Which is: 1
  0u
    Which is: 0

[  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_Basic
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_Basic (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_KGreaterThanSize (0 ms)
[ RUN      ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer
[       OK ] FreqBufferExtendedTest.GetTopKFrequent_EmptyBuffer (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_Basic
[       OK ] FreqBufferExtendedTest.pop_least_used_Basic (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals
[       OK ] FreqBufferExtendedTest.pop_least_used_MultipleRemovals (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_MoreThanSize
[       OK ] FreqBufferExtendedTest.pop_least_used_MoreThanSize (0 ms)
[ RUN      ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:297: Failure
Expected equality of these values:
  buffer.size()
    Which is: 0
  1u
    Which is: 1

unknown file: Failure
C++ exception with description "Key not found in FreqBuffer" thrown in the test body.

[  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative (0 ms)
[----------] 10 tests from FreqBufferExtendedTest (0 ms total)

[----------] Global test environment tear-down
[==========] 13 tests from 2 test suites ran. (0 ms total)
[  PASSED  ] 11 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] FreqBufferExtendedTest.Resize_ZeroEdgeCase
[  FAILED  ] FreqBufferExtendedTest.pop_least_used_ZeroOrNegative

 2 FAILED TESTS
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Failed.
"model4_tests" end time: Jan 31 22:23 +06
"model4_tests" time elapsed: 00:00:00
----------------------------------------------------------

Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model5_tests
7/11 Testing: model5_tests
7/11 Test: model5_tests
Command: ""
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
"model5_tests" start time: 
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"model5_tests" end time: Jan 31 22:23 +06
"model5_tests" time elapsed: 00:00:00
----------------------------------------------------------

Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model6_tests
8/11 Testing: model6_tests
8/11 Test: model6_tests
Command: ""
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
"model6_tests" start time: 
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"model6_tests" end time: Jan 31 22:23 +06
"model6_tests" time elapsed: 00:00:00
----------------------------------------------------------

9/11 Testing: model7_tests
9/11 Test: model7_tests
Command: "/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model7_tests"
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
"model7_tests" start time: Jan 31 22:23 +06
Output:
----------------------------------------------------------
Running main() from /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 13 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 3 tests from FreqBufferBasicTest
[ RUN      ] FreqBufferBasicTest.CapacityAndSize
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:22: Failure
Expected: (buffer.size()) <= (3u), actual: 4 vs 3

[  FAILED  ] FreqBufferBasicTest.CapacityAndSize (0 ms)
[ RUN      ] FreqBufferBasicTest.PutAndGet
[       OK ] FreqBufferBasicTest.PutAndGet (0 ms)
[ RUN      ] FreqBufferBasicTest.FrequencyIncrementsOnGet
/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:59: Failure
Expected: buffer.get("C") throws an exception of type std::runtime_error.
  Actual: it throws nothing.

/Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/test.cpp:64: Failure
Expected equality of these values:
  buffer.size()
    Which is: 4
  3u
    Which is: 3

[  FAILED  ] FreqBufferBasicTest.FrequencyIncrementsOnGet (0 ms)
[----------] 3 tests from FreqBufferBasicTest (0 ms total)

[----------] 10 tests from FreqBufferExtendedTest
[ RUN      ] FreqBufferExtendedTest.Resize_IncreaseCapacity
[       OK ] FreqBufferExtendedTest.Resize_IncreaseCapacity (0 ms)
[ RUN      ] FreqBufferExtendedTest.Resize_DecreaseCapacity
<end of output>
Test time =   0.01 sec
----------------------------------------------------------
Test Failed.
"model7_tests" end time: Jan 31 22:23 +06
"model7_tests" time elapsed: 00:00:00
----------------------------------------------------------

Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model8_tests
10/11 Testing: model8_tests
10/11 Test: model8_tests
Command: ""
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
"model8_tests" start time: 
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"model8_tests" end time: Jan 31 22:23 +06
"model8_tests" time elapsed: 00:00:00
----------------------------------------------------------

Unable to find executable: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build/model9_tests
11/11 Testing: model9_tests
11/11 Test: model9_tests
Command: ""
Directory: /Users/ittehad/Documents/Coding/Python/Turing/Tester_cpp_codebench/tasks/473651/build
"model9_tests" start time: 
Output:
----------------------------------------------------------
<end of output>
Test time =   0.00 sec
----------------------------------------------------------
Test Passed.
"model9_tests" end time: Jan 31 22:23 +06
"model9_tests" time elapsed: 00:00:00
----------------------------------------------------------

End testing: Jan 31 22:23 +06
